---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

```{r setup}
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Results

```{r}
targets::tar_read(df_stats_by_metabolite) |>
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) |>
  select(Metabolite = metabolite, `Mean SD` = MeanSD) |>
  knitr::kable(caption = "Descriptive statistics of the metabolites.")
```

```{r}
tar_read(fig_metabolite_distribution)
```

## Building the model

```{r}
lipidomics_wide <-
  lipidomics |>
  column_values_to_snake_case(metabolite) |>
  metabolites_to_wider()
lipidomics_wide
```

## Running multiple models

```{r}
model_estimates <- lipidomics |> calculate_estimates()
model_estimates
```

## Fixing metabolite names

```{r}
lipidomics |> 
    select(metabolite) |> 
    mutate(term=metabolite) |> 
    column_values_to_snake_case(term) |> 
    mutate(term = str_c("metabolite_", term)) |> 
    distinct(metabolite, term) |> 
    right_join(model_estimates, by = "term")
```
